services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    container_name: infinite-simon-backend
    ports:
      - 3001:3001
    volumes:
      - ./db:/app/prisma/db
    environment:
      - DATABASE_URL=file:./db/dev.db
      - JWT_SECRET=REPLACE_WITH_A_LONG_RANDOM_SECRET
      - RESEND_API_KEY=re_xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - FRONTEND_URL=http://localhost

    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: infinite-simon-frontend
    ports:
      - 80:80
    environment:
      - REACT_APP_SERVER_URL=http://localhost:3001
    restart: unless-stopped
    depends_on:
      - backend
